// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoBanco.Infrastructure.Data;

#nullable disable

namespace ProjetoBanco.Infrastructure.Migrations
{
    [DbContext(typeof(BancoDBContext))]
    [Migration("20260624140509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBanco.Core.Models.Conta", b =>
                {
                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Numero");

                    b.ToTable("Contas");

                    b.HasDiscriminator<string>("TipoConta").HasValue("Conta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Core.Models.HistoricoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroConta");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("ProjetoBanco.Core.Models.ContaCorrente", b =>
                {
                    b.HasBaseType("ProjetoBanco.Core.Models.Conta");

                    b.Property<decimal>("LimiteChequeEspecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxaManutencao")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("ContaCorrente");
                });

            modelBuilder.Entity("ProjetoBanco.Core.Models.ContaPoupanca", b =>
                {
                    b.HasBaseType("ProjetoBanco.Core.Models.Conta");

                    b.Property<decimal>("TaxaRendimento")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("ContaPoupanca");
                });

            modelBuilder.Entity("ProjetoBanco.Core.Models.HistoricoResposta", b =>
                {
                    b.HasOne("ProjetoBanco.Core.Models.Conta", null)
                        .WithMany("Historico")
                        .HasForeignKey("NumeroConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoBanco.Core.Models.Conta", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
